#VERSION: 0.0.1

#this only works back to versions: 1.7.x
#view list of downloads here: #http://code.google.com/p/phantomjs/downloads/list?can=1
#http://www.ansibleworks.com/docs/modules.html#id185
---
- hosts: all
  vars:
    phantom_version: 1.9.2
  tasks:
  - name: ensure libfontconfig is installed
    apt: pkg=libfontconfig1 state=latest
  - name: ensure bzip2 is installed
    apt: pkg=bzip2 state=latest
  - name: get architecture
    shell: uname -m
    register: arch
  - name: download phantomjs
    get_url: url=http://phantomjs.googlecode.com/files/phantomjs-${phantom_version}-linux-{{ item }}.tar.bz2 dest=/tmp/pjs.tar.bz2 force=yes
    with_items: arch.stdout_lines #this feels super hacky, there is probably a better way
  - name: bunzip2 phantomjs
    command: bunzip2 -f /tmp/pjs.tar.bz2
  - name: untar phantomjs
    command: tar xf /tmp/pjs.tar -C /tmp
  - name: installing phantomjs
    command: mv -f /tmp/phantomjs-${phantom_version}-linux-{{ item }}/bin/phantomjs /usr/local/bin/phantomjs-${phantom_version}
    with_items: arch.stdout_lines
  - name: symlinking phantomjs
    file: src=/usr/local/bin/phantomjs-${phantom_version} dest=/usr/local/bin/phantomjs state=link
  - name: removing tar file
    file: path=/tmp/pjs.tar state=absent
